/// Sockets emit events
const DRIVER_RIDE_ACCEPTANCE = 'driver-ride-acceptance';
const DRIVER_RIDE_DISPATCH = 'driver-ride-dispatch';
const DRIVER_LOCATION_UPDATE = 'driver-location-update';
const DRIVER_ACTIVENESS_UPDATE = 'driver-activeness-update';
const CUSTOMER_RIDE_REQUEST = 'customer-ride-request';
const RIDE_REQUEST_DRIVER_NOTIFICATION = 'ride-request-driver-notification';
const RIDE_CANCELLATION = 'ride-cancellation';
const RIDE_INITIATION = 'ride-initiation';
const RIDE_COMPLETION = 'ride-completion';
const RIDE_ON_DISPATCH = 'ride-on-dispatch';
const RIDE_ON_TRIP = 'ride-on-trip';
const NEW_USER = 'new-user';
const CUSTOMER_RIDE_DISPATCH = 'customer-ride-dispatch';